### ISSUE TITLE
license 

### ISSUE THREAD

**Issue by Austin117** [taterjuice/Vivrant.DatePicker#1]
TaterJuice, 

What is your license for usage of your code?
I wanted to use your https://github.com/taterjuice/Vivrant.DatePicker/blob/master/Vivrant.DatePicker/PresenterBase.cs to help me setup my MVVM CSHTML5 commercial app. Is that ok?
Thanks so much!
Austin

**Comment by itsTurk** [comment]
It's boilerplate code, you're welcome to use it.

**Comment by Austin117** [comment]
Got it. Thanks!
